//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 3DCreator.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TOOLFORM                    101
#define IDR_MAINFRAME                   128
#define IDR_MY3DCRTYPE                  129
#define IDR_POPUP_MENU                  131
#define IDD_LOFT                        132
#define IDR_LOFT_MENU                   133
#define IDD_EDIT_MATERIAL               134
#define IDD_LOFTLENGTH                  135
#define IDD_SCENE_PREFERENCE            136
#define IDD_RENDER                      137
#define IDD_RENDER_RESULT               139
#define IDR_RENDER                      140
#define IDC_NEW_CUBE                    1001
#define IDC_NEW_CONE                    1002
#define IDC_NEW_SPHERE                  1003
#define IDC_NEW_CYLINDER                1004
#define IDC_INTERSECT                   1005
#define IDC_DIFFERENCE                  1006
#define IDC_UNION                       1007
#define IDC_SELECT_CREATE               1008
#define IDC_SELECT_BOOL_OBJECT          1009
#define IDC_POSITION                    1014
#define IDC_POS_X                       1015
#define IDC_POS_Y                       1016
#define IDC_POS_Z                       1017
#define IDC_STATIC_POS_Z                1018
#define IDC_STATIC_POS_Y                1019
#define IDC_STATIC_POS_X                1020
#define IDC_NEW_LIGHT                   1021
#define IDC_PROPERTY                    1022
#define IDC_PROPERTY1                   1023
#define IDC_PROPERTY2                   1024
#define IDC_PROPERTY3                   1025
#define IDC_STATIC_PROPERTY1            1026
#define IDC_STATIC_PROPERTY2            1027
#define IDC_STATIC_PROPERTY3            1028
#define IDC_BASIC                       1029
#define IDC_STATIC_NAME                 1030
#define IDC_STATIC_COLOR                1031
#define IDC_NAME                        1032
#define IDC_COLOR                       1033
#define IDC_CASTSHADOW                  1036
#define IDC_MATERIAL                    1037
#define IDC_APPLY                       1039
#define IDC_TAB                         1042
#define IDC_POSX                        1043
#define IDC_POSY                        1044
#define IDC_STATUS                      1045
#define IDC_KA                          1046
#define IDC_KD                          1047
#define IDC_KS                          1048
#define IDC_N                           1049
#define IDC_KR                          1050
#define IDC_KT                          1051
#define IDC_RR                          1052
#define IDC_TEXTURE                     1053
#define IDC_MAP                         1054
#define IDC_SCALE                       1055
#define IDC_BUMP                        1056
#define IDC_BR                          1057
#define IDC_LOADMAP                     1058
#define IDC_STATIC_SCALE                1059
#define IDC_STATIC_BR                   1060
#define IDC_LENGTH                      1061
#define IDC_AINTENSION                  1062
#define IDC_ACOLOR                      1063
#define IDC_BACKMAP                     1064
#define IDC_LOADBACK                    1066
#define IDC_BKCOLOR                     1067
#define IDC_BACKBITMAP                  1068
#define IDC_WIDTH                       1070
#define IDC_HEIGHT                      1071
#define IDC_VIEW                        1073
#define IDC_ANTIALIAS                   1074
#define IDC_LOADBUMP                    1075
#define IDC_BUMPMAP                     1076
#define IDC_BSCALE                      1077
#define IDC_SBSCALE                     1078
#define ID_SELECTING                    32771
#define ID_VIEW_MOVE                    32772
#define ID_VIEW_SCALE                   32773
#define ID_VIEW_ROATATE                 32774
#define ID_EDIT_MOVE                    32775
#define ID_EDIT_SCALE                   32776
#define ID_EDIT_ROTATE                  32777
#define ID_VIEW_ROTATE                  32778
#define ID_ZOOM                         32779
#define ID_ELIMINATE                    32780
#define ID_FRONT                        32781
#define ID_BACK                         32782
#define ID_TOP                          32783
#define ID_BOTTOM                       32784
#define ID_LEFT                         32785
#define ID_RIGHT                        32786
#define ID_PERSPECTIVE                  32787
#define ID_VIEW_ZOOM                    32789
#define ID_EDIT_DELETE                  32790
#define ID_EDIT_LOFT                    32791
#define ID_LOFT_DRAWSHAPE               32793
#define ID_CIRCLELOFT                   32794
#define ID_LINELOFT                     32795
#define ID_EXITLOFT                     32796
#define ID_LOFT_MOVEVIEW                32797
#define ID_LOFT_ZOOMVIEW                32798
#define ID_LOFT_EDIT                    32799
#define ID_LOFT_MOVE                    32800
#define ID_LOFT_ROTATE                  32801
#define ID_LOFT_SCALE                   32802
#define ID_SCENE_RENDER                 32804
#define ID_SCENE_PREFERENCE             32805
#define ID_RENDER_SAVE                  32807
#define ID_RENDER_CLOSE                 32808
#define ID_WIREFRAME                    32809
#define ID_SMOOTH                       32810
#define ID_POS_X                        61449
#define ID_POS_Y                        61450
#define ID_POS_Z                        61451

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
